version: 2
updates:
  # PHP dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jochembeetz"
    assignees:
      - "jochembeetz"
    labels:
      - "dependencies"
      - "php"
    commit-message:
      prefix: "composer"
      include: "scope"
    groups:
      laravel:
        patterns:
          - "laravel/*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "phpunit/*"
          - "mockery/*"
          - "fakerphp/*"
          - "nunomaduro/*"
        update-types:
          - "minor"
          - "patch"
      dev-tools:
        patterns:
          - "larastan/*"
          - "laravel/pint"
          - "laravel/sail"
          - "laravel/pail"
        update-types:
          - "minor"
          - "patch"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jochembeetz"
    assignees:
      - "jochembeetz"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "npm"
      include: "scope"
    groups:
      build-tools:
        patterns:
          - "vite"
          - "laravel-vite-plugin"
          - "@tailwindcss/*"
          - "tailwindcss"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "concurrently"
          - "axios"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jochembeetz"
    assignees:
      - "jochembeetz"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
